### model
model_name_or_path: saves/full_sft/

### method
stage: sft
do_eval: 1
do_train: 0
finetuning_type: full

### dataset
dataset: ds
template: llama3
cutoff_len: 1600
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/full_sft_o/
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true


### eval
train_size: 0.8
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 10000
predict_with_generate: 1